# Generated by Django 3.1.3 on 2021-06-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210618_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x909902a92a6e30515b1285fcafc3e9d5', max_length=128),
        ),
    ]
