# Generated by Django 3.1.3 on 2021-06-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210618_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0xaa98d73a3f4d4ea0bba0ee6db19ed095', max_length=128),
        ),
    ]
