# Generated by Django 3.1.3 on 2021-06-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210619_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x72a2d9ad36ba21a516949469514fb37c', max_length=128),
        ),
    ]
