# Generated by Django 3.1.3 on 2021-06-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210621_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x6861acb230e1b9daa3f888bc5ea80e02', max_length=128),
        ),
    ]
