# Generated by Django 3.1.3 on 2021-06-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210627_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x7ba6270336991a5eb45ec4e605174092', max_length=128),
        ),
    ]
