# Generated by Django 3.1.3 on 2021-06-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('date',), name='unique_slot'),
        ),
    ]
